version: "3.9"

services:
  app:
    container_name: payload-analyzer
    build:
      context: .
    environment:
      - PYTHONUNBUFFERED=1
      - METRICS_PREFIX=payload_analyzer
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - backend


# Uncomment the following section to enable Prometheus monitoring for local development
#   prometheus:
#     image: prom/prometheus:v2.52.0
#     container_name: prometheus
#     # volumes:
#     #   - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#     ports:
#       - "9090:9090"
#     depends_on:
#       - app
#     networks:
#       - backend

networks:
  backend:
    driver: bridge
