apiVersion: v1
kind: Service
metadata:
  name: payload-analyzer
spec:
  type: LoadBalancer
  selector:
    app: payload-analyzer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8081
---